config/routes.rb
NewAbsent::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  match 'users/sign_up' => redirect('/')

  get "home/index"
  post "/get_in" => "home#update_get_in"
  put "/get_out" => "home#update_get_out"
  root :to => 'home#index'

end

app/models/absent.rb
class Absent < ActiveRecord::Base
  attr_accessor :current_user
  attr_accessible :time_out, :time_in, :working_date, :user_id
  belongs_to :user
  before_create :check_in
  before_update :check_out
  
  delegate :name, :address, :phone, to: :user, prefix: true, allow_nil: true

  protected
  
  def check_in
  cond = Absent.where('user_id = ? AND DATE(working_date) = ?', current_user.id ,Date.today)
    if cond.count < 1
      p "you can get in"
      return true
    else
      p "you can not get in"
      return false
    end
  end
  
  def check_out
  cond = Absent.where('user_id = ? AND DATE(working_date) = ?', current_user.id ,Date.today).first
  p cond
    if cond.time_out.blank? && ((Time.now.strftime("%H").to_i - cond.time_in.strftime("%H").to_i) >= WorkingTime.last.hour)
      p "you can update"
      self.time_out = Time.now
    else
      p "you can not update"
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :absents
  #  has_one :employee
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
    :recoverable, :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :address, :phone
  attr_accessible :provider, :uid
  validates :phone, :numericality => true

end

app/models/working_time.rb
class WorkingTime < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
#  def after_sign_in_path_for(resource)
#    p current_user
#    p current_admin_user
##    if resource.is_a?(User)
#      index_home_path
##    elsif resource.is_a?(AdminUser)
##      admin_root_path
##    end
#  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery :except => [:update_get_in, :update_get_out]
  #  before_filter :authenticate_user!

  def index
    @time_working = WorkingTime.last
    @users = Absent.where(' working_date BETWEEN ? AND ?' ,  DateTime.now.beginning_of_day.strftime("%Y-%m-%d %H:%M:%S"), DateTime.now.end_of_day.strftime("%Y-%m-%d %H:%M:%S")).all
    @absent = Absent.where('user_id = ? AND working_date BETWEEN ? AND ?' ,  current_user.id,  DateTime.now.beginning_of_day.strftime("%Y-%m-%d %H:%M:%S"), DateTime.now.end_of_day.strftime("%Y-%m-%d %H:%M:%S")).last unless current_user.blank?
    @user_ip = request.remote_ip

    respond_to do |format|
      format.html
      format.js
      format.json {render json: @absent}
    end
  end
  
  def update_get_in
    @absent = Absent.new(params["absent"])
    @absent.current_user = current_user
    if @absent.save
      flash[:alert] = "Check In Succes"
      p "Get In Succes"
    else
      flash[:alert] = "You have done check in"
      p "Get In Failed"
    end
  end
  
  def update_get_out
    @absent = Absent.where('user_id = ? AND working_date BETWEEN ? AND ?' ,  current_user.id,  DateTime.now.beginning_of_day.strftime("%Y-%m-%d %H:%M:%S"), DateTime.now.end_of_day.strftime("%Y-%m-%d %H:%M:%S")).last
    @absent.current_user = current_user
    if @absent.update_attributes(params["absent"])
      flash[:alert] = "Check Out Succes"
      p "Get Out Succes"
    else
      flash[:alert] = "You can't check out now "
      p "Get Out Failed"
    end
  end
 
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    auth = request.env["omniauth.auth"]
    p auth

    if user = User.find_by_uid(auth.uid)
      sign_in(user)
    elsif user_signed_in?
      current_user.update_attributes(:uid => auth.uid, :provider => auth.provider)
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>

  <h1>Your Profile</h1>
  <table class="table table-striped">
    <tr>
      <td>Name</td>
      <td>:</td>
      <td><%= current_user.name %></td>
    </tr>
    <tr>
      <td>Email</td>
      <td>:</td>
      <td><%= current_user.email %></td>
    </tr>
    <tr>
      <td>Address</td>
      <td>:</td>
      <td><%= current_user.address %></td>
    </tr>
    <tr>
      <td>Phone</td>
      <td>:</td>
      <td><%= current_user.phone %></td>
    </tr>
    <% if @user_ip == "127.0.0.1" %>
      <tr>
        <td>
          <button class="btn btn-primary get_in" id="get_in">Check In</button>
          <button class="btn btn-primary get_out" id="get_out">Check Out</button>
        </td>
        <td></td>
        <td></td>
      </tr>
    <% else %>
      <tr><td></td></tr>
      <tr>
        <td class="outside">
          You are outside the area
        </td>
      </tr>
    <% end %>
    <tr>
      <% if !@absent.nil? %>
        <td>Check In</td>
        <td>:</td>
        <td><%= @absent.time_in.strftime("%H:%M") %></td>
      </tr>
      <tr>
        <td>Time Remaining</td>
        <td>:</td>
        <% tm_work_hour = ((@absent.time_in + @time_working.hour.hours - 7.hour).to_i - Time.now.to_i) / 3600 %>
        <% tm_work_minute = (((@absent.time_in + @time_working.hour.hours).to_i - Time.now.to_i) % 3600) / 60 %>
        <td><%=  "#{tm_work_hour} : #{tm_work_minute}" %></td>
        <tr>
          <td>Check Out</td>
          <td>:</td>
          <td><%= (@absent.time_in + @time_working.hour.hours).strftime("%H:%M") %></td>
        </tr>
      </tr>
    <% end %>
  </table>

  <script type="text/javascript" src="/assets/clock.js"></script>
  <script>

    $(document).ready(function(){

      $('.get_in').click(function(){
        $(this).attr('disabled','disabled')
        $('.get_out').removeAttr('disabled','disabled')
        $.ajax({
          url: "<%= get_in_path %>",
          type: 'POST',
          data: { "absent[working_date]": "<%= DateTime.now.strftime("%Y-%m-%d %H:%M:%S") %>", "absent[time_in]": "<%= Time.now.strftime("%H:%M:%S") %>", "absent[user_id]": <%= current_user.id %> },
          context: document.body
        }).done(function() {
          $(this).addClass("done");
        });
      });

      $('.get_out').click(function(){
        $(this).attr('disabled','disabled');
        $('.get_in').removeAttr('disabled','disabled');
        $.ajax({
          url: "<%= get_out_path %>",
          type: 'PUT',
          data: { "absent[time_out]": "<%= Time.now.strftime("%H:%M:%S") %>"},
          context: document.body
        }).done(function() {
          $(this).addClass("done");
        });
      });
    });

  </script>

<% else %>
  <h1>You must sign in first</h1>
  <br />
  <h3>The number of employees who have entered today <%= @users.count %></h3>
  <table class="table table-striped">
    <% if !@users.blank? && !@time_working.blank? %>
      <tr>
        <th>Name</th>
        <th>Check In</th>
        <th>Time Remaining</th>
        <th></th>
        <th></th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.user[:name] %></td>
          <td><%= user[:time_in].strftime("%H:%M") %></td>
          <% tm_work_hour = ((user.time_in + @time_working.hour.hours - 7.hour).to_i - Time.now.to_i) / 3600 %>
          <% tm_work_minute = (((user.time_in + @time_working.hour.hours).to_i - Time.now.to_i) % 3600) / 60 %>
          <td><%=  "#{tm_work_hour} : #{tm_work_minute}" %></td>
        </tr>
      <% end %>
    <% end %>
  </table>

<% end %>

<script type="text/javascript">
  $(document).ready(function(){

<% if @absent.nil? %>
      $('.get_in').show();
      $('.get_out').hide();
<% elsif @absent.time_out.nil? %>
      $('.get_in').hide();
      $('.get_out').show();
<% else %>
      $('.get_in').hide();
      $('.get_out').hide();
<% end %>

<% if DateTime.now.strftime("%H").to_i >= @time_working.first_check_in && DateTime.now.strftime("%H").to_i <= @time_working.last_check_in %>
      $('.get_in').removeAttr('disabled','disabled');
<% else %>
      $('.get_in').attr('disabled','disabled');
<% end %>

<% if DateTime.now.strftime("%H").to_i >= @time_working.first_check_out && DateTime.now.strftime("%H").to_i <= @time_working.last_check_out %>
      $('.get_out').removeAttr('disabled','disabled');
<% else %>
      $('.get_out').attr('disabled','disabled');
<% end %>
  });
</script>

app/views/home/update_get_in.js.erb
$('.get_out').show();
$('.get_in').hide();
alert("<%= flash[:alert] %>");

app/views/home/update_get_out.js.erb
$('.get_in').hide();
$('.get_out').hide();
alert("<%= flash[:alert] %>");
$('.get_out').removeAttr('disabled','disabled');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewAbsent</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= yield %>

  </body>

</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "NewAbsent" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

<%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container container_header">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand center_tab" href="#">Attendance Application</a>
          <div class="container nav-collapse">
            <div class="clock">
              <div id="Date"></div>
              <ul>
                <li class="hour" id="hours"></li>
                <li class="hour" id="point">:</li>
                <li class="hour" id="min"></li>
                <li class="hour" id="point">:</li>
                <li class="hour" id="sec"></li>
              </ul>
            </div>
            <!--
            <ul class="nav center_tab">
<%#*<li class="center_tab"><%= link_to "Link1", "/path1"  %></li>%>
<%#*<li class="center_tab"><%= link_to "Link2", "/path2"  %></li>%>
<%#*<li class="center_tab"><%= link_to "Link3", "/path3"  %></li>%>
            </ul>
            -->
            <%#*<marquee class="marr"><image class="dolph" src="assets/dolph.gif" height="35" width="40"></image> </marquee>%>
            <image class="img-circle" src="assets/pushjaw.png" height="50" width="50"></image>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span9">
          <%#= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="span3">
          <div class="well sidebar-nav">
            <h3>User</h3>
            <ul class="nav nav-list">
                <% if user_signed_in? %>
                  <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %></li>
                  <li><%= link_to "Connect to Facebook", user_omniauth_authorize_path(:facebook) %></li>
                <% else %>
                  <li><%= link_to "Sign In",  new_user_session_path  %></li>
                <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <script src="/assets/clock.js" type="text/javascript"/></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  </body>
</html>